package main

import (
	"sort"
	"strings"
)

// catalogPath is the agent-facing artifact, kept at the repo root: it is the
// path anchor (entries resolve relative to this file's directory, so a bare
// "leadership/about.md" is correct in hq and resolves to "hq/leadership/..."
// from a repo that consumes hq as a subtree), and it is a maintained file whose
// visibility is the reminder to keep it current.
const catalogPath = ".catalog.md"

// render produces the full .catalog.md from the store's rows: the header,
// then entries grouped under "## <dir>/" section headers and emitted as
// "### <path>" stanzas. Profiles are written as single-line paragraphs and
// left for bin/format (Prettier) to wrap, the same discipline as every other
// Markdown file in the repo.
//
// The header is always defaultHeader() — the store holds no header field, so
// there is nothing per-repo to preserve. The header is generic boilerplate
// describing what the file is, not project-specific prose anyone hand-tunes.
func render(rows []profileRow) string {
	var b strings.Builder
	b.WriteString(strings.TrimRight(defaultHeader(), "\n"))
	b.WriteString("\n")

	sorted := make([]profileRow, len(rows))
	copy(sorted, rows)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].path < sorted[j].path })

	lastDir := ""
	for _, r := range sorted {
		dir := dirOf(r.path)
		if dir != lastDir {
			b.WriteString("\n## ")
			b.WriteString(dir)
			b.WriteString("\n")
			lastDir = dir
		}
		b.WriteString("\n### ")
		b.WriteString(r.path)
		b.WriteString("\n\n")
		b.WriteString(strings.TrimSpace(r.profile))
		b.WriteString("\n")
	}
	return b.String()
}

func dirOf(path string) string {
	if i := strings.LastIndex(path, "/"); i >= 0 {
		return path[:i] + "/"
	}
	return "(root)"
}

func defaultHeader() string {
	return strings.TrimSpace(`
# Catalog

This is the index of the durable content in this repo. Each entry below is a
profile: read it at the start of a conversation, then load a document only when
your task matches its profile — you don't need to read the others.

Paths are relative to this file's own location. In this repo the catalog sits
at the root, so `+"`leadership/about.md`"+` is correct as written. In a repo
that consumes this one as a subtree, the catalog sits in a subdirectory, so the
same entry resolves relative to that subdirectory.

Generated by `+"`catalog update`"+` from the source documents. Run
`+"`catalog status`"+` to find entries that have gone stale.
`) + "\n"
}
